import { Badge, EmptyState, PageHeader } from "@/components/ui";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { inviteTeacherAccess, resendAccessInvitation, setInstitutionalAccess, updateTeacherAdmin } from "@/app/admin/actions";

export default async function AdminTeachersPage({ searchParams }: { searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const query = await searchParams;
  await requireRole("admin");
  const supabase = await createClient();
  const [{ data: teachers }, { data: invitations }] = await Promise.all([
    supabase.from("teachers").select("id,profile_id,active,phone_whatsapp,professional_description,created_at,profiles(full_name,preferred_name,phone_whatsapp)").order("created_at", { ascending: false }).limit(120),
    supabase.from("access_invitations").select("id,email,full_name,status,sent_at,accepted_at,last_error").eq("role", "teacher").order("created_at", { ascending: false }).limit(50),
  ]);
  return (
    <>
      <PageHeader eyebrow="Admin • Pessoas" title="Professores" description="Cadastre, edite e gerencie o acesso da equipe pedagógica sem apagar o histórico das missões e correções." />
      {query.erro && <div className="form-message form-error">{query.erro}</div>}
      {query.sucesso && <div className="form-message form-success">{query.sucesso}</div>}
      <div className="grid-2">
        <section className="panel"><div className="panel-head"><div><h2>Novo professor</h2><p>O professor recebe um link para definir a própria senha.</p></div></div><form action={inviteTeacherAccess} className="form-stack"><div className="field"><label>Nome completo *</label><input className="input" name="fullName" required /></div><div className="field"><label>Nome preferido</label><input className="input" name="preferredName" /></div><div className="field"><label>E-mail *</label><input className="input" type="email" name="email" required /></div><div className="field"><label>WhatsApp</label><input className="input" name="phone" /></div><button className="button button-primary" type="submit">Cadastrar e enviar acesso</button></form></section>
        <section className="panel"><div className="panel-head"><div><h2>Convites recentes</h2></div></div>{invitations?.length ? <div className="form-stack">{invitations.map((invite: any) => <article className="access-invite-card" key={invite.id}><div className="flex space-between gap-8 wrap"><div><strong>{invite.full_name}</strong><p>{invite.email}</p></div><Badge tone={invite.status === "accepted" ? "green" : invite.status === "error" ? "pink" : "yellow"}>{invite.status}</Badge></div>{invite.status !== "accepted" && <form action={resendAccessInvitation}><input type="hidden" name="invitationId" value={invite.id} /><input type="hidden" name="returnTo" value="/admin/professores" /><button className="button button-secondary button-small" type="submit">Reenviar link</button></form>}</article>)}</div> : <p className="muted">Nenhum convite recente.</p>}</section>
      </div>
      <section className="panel"><div className="panel-head"><div><h2>Equipe cadastrada</h2></div></div>{teachers?.length ? <div className="people-admin-grid">{teachers.map((teacher: any) => <article className="person-admin-card" key={teacher.id}><div className="flex space-between gap-8 wrap"><div><h3>{teacher.profiles?.preferred_name || teacher.profiles?.full_name}</h3><p>{teacher.profiles?.full_name}</p></div><Badge tone={teacher.active ? "green" : "neutral"}>{teacher.active ? "Ativo" : "Acesso retirado"}</Badge></div><p>{teacher.professional_description || "Descrição profissional não preenchida"}</p><small className="muted">{teacher.phone_whatsapp || teacher.profiles?.phone_whatsapp || "Sem telefone"}</small><details className="plan-editor"><summary>Editar professor</summary><form action={updateTeacherAdmin} className="form-stack"><input type="hidden" name="teacherId" value={teacher.id} /><input type="hidden" name="profileId" value={teacher.profile_id} /><div className="field"><label>Nome completo</label><input className="input" name="fullName" defaultValue={teacher.profiles?.full_name || ""} required /></div><div className="field"><label>Nome preferido</label><input className="input" name="preferredName" defaultValue={teacher.profiles?.preferred_name || ""} /></div><div className="field"><label>WhatsApp</label><input className="input" name="phone" defaultValue={teacher.phone_whatsapp || teacher.profiles?.phone_whatsapp || ""} /></div><div className="field"><label>Descrição profissional</label><textarea className="textarea" name="professionalDescription" defaultValue={teacher.professional_description || ""} /></div><button className="button button-secondary button-small" type="submit">Salvar alterações</button></form></details><form action={setInstitutionalAccess}><input type="hidden" name="profileId" value={teacher.profile_id} /><input type="hidden" name="role" value="teacher" /><input type="hidden" name="enabled" value={teacher.active ? "false" : "true"} /><input type="hidden" name="returnTo" value="/admin/professores" /><button className={`button button-small ${teacher.active ? "button-danger" : "button-primary"}`} type="submit">{teacher.active ? "Retirar acesso de professor" : "Reativar professor"}</button></form></article>)}</div> : <EmptyState title="Nenhum professor cadastrado" description="A equipe aparecerá aqui." />}</section>
    </>
  );
}
