"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { getCurrentTeacher } from "@/lib/teacher";
import { planLimitErrorMessage } from "@/lib/plan-usage";

const agendaSchema = z.object({
  idempotencyKey: z.string().min(8).max(160), studentId: z.string().uuid(), title: z.string().trim().min(2).max(160),
  description: z.string().trim().max(1200).optional(), eventType: z.enum(["meeting","family_meeting","review","assessment","deadline","reminder","class","other"]),
  status: z.enum(["scheduled","confirmed","completed","cancelled"]), startsAt: z.string().min(10), endsAt: z.string().optional(), meetingUrl: z.string().trim().max(1200).optional(), location: z.string().trim().max(300).optional(),
  recurrence: z.enum(["once","weekly"]), repeatWeeks: z.coerce.number().int().min(2).max(24),
}).superRefine((value, ctx) => {
  if (value.meetingUrl) { try { const url=new URL(value.meetingUrl); if(url.protocol!=="https:") throw new Error(); } catch { ctx.addIssue({code:z.ZodIssueCode.custom,path:["meetingUrl"],message:"Use um link HTTPS válido para a reunião."}); } }
  if (value.recurrence === "weekly" && !["class","review"].includes(value.eventType)) ctx.addIssue({code:z.ZodIssueCode.custom,path:["recurrence"],message:"A repetição semanal é exclusiva para Aula ou Revisão. Reuniões com a família continuam flexíveis e avulsas."});
  if (value.recurrence === "weekly" && ["completed","cancelled"].includes(value.status)) ctx.addIssue({code:z.ZodIssueCode.custom,path:["status"],message:"Uma nova série semanal deve começar como Agendada ou Confirmada."});
});
function bahiaDateTime(value?: string) { if(!value?.trim()) return null; const normalized=value.length===16?`${value}:00`:value; const date=new Date(`${normalized}-03:00`); return Number.isNaN(date.getTime())?null:date.toISOString(); }
function agendaDateLabel(value:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Bahia"}).format(new Date(value));}
function eventKindLabel(eventType?:string|null){if(eventType==="class")return"aula";if(eventType==="review")return"revisão";if(eventType==="family_meeting"||eventType==="meeting")return"reunião";if(eventType==="assessment")return"avaliação";return"encontro";}
async function linkedGuardiansForStudent(supabase:any,studentId:string){const {data,error}=await supabase.rpc("teacher_linked_guardian_names");if(error){console.error("Falha ao localizar responsáveis vinculados para aviso de agenda",error.code);return [] as any[];}return(data??[]).filter((row:any)=>row.student_id===studentId&&row.guardian_id);}
async function sendAgendaFamilyNotice({supabase,studentId,studentName,title,eventType,startsAt,eventId,status}:{supabase:any;studentId:string;studentName:string;title:string;eventType:string;startsAt:string;eventId:string;status:"scheduled"|"confirmed"|"completed"|"cancelled"}){const guardians=await linkedGuardiansForStudent(supabase,studentId);if(!guardians.length)return{attempted:0,failed:0};const when=agendaDateLabel(startsAt);const kind=eventKindLabel(eventType);let failed=0;for(const guardian of guardians){const feminine=["reunião","aula","avaliação","revisão"].includes(kind);const statusText=status==="cancelled"?`foi cancelad${feminine?"a":"o"}`:status==="confirmed"?`foi confirmad${feminine?"a":"o"}`:"foi agendado";const subject=status==="scheduled"?`${kind.charAt(0).toUpperCase()}${kind.slice(1)} de ${studentName} em ${when}`:`Atualização no encontro de ${studentName}`;const body=status==="scheduled"?`Olá, ${guardian.guardian_name||"responsável"}! ${studentName} tem ${kind} marcada para ${when}: “${title}”. Os detalhes e o acesso ficam na Agenda da Família.`:`Olá, ${guardian.guardian_name||"responsável"}! O encontro “${title}” de ${studentName}, previsto para ${when}, ${statusText}. Confira a Agenda da Família para a situação atual.`;const {error}=await supabase.rpc("send_curio_family_message",{p_student_id:studentId,p_guardian_id:guardian.guardian_id,p_subject:subject,p_body:body,p_action_label:"Ver agenda",p_action_url:"/familia/agenda",p_request_key:`agenda:${eventId}:${status}:${guardian.guardian_id}`});if(error){failed++;console.error("Falha ao enviar aviso interno de agenda",error.code);}}return{attempted:guardians.length,failed};}
async function sendAgendaFamilySeriesNotice({supabase,studentId,studentName,title,eventType,startsAt,seriesId,weeks}:{supabase:any;studentId:string;studentName:string;title:string;eventType:string;startsAt:string;seriesId:string;weeks:number}){const guardians=await linkedGuardiansForStudent(supabase,studentId);if(!guardians.length)return{attempted:0,failed:0};const first=agendaDateLabel(startsAt);const weekday=new Intl.DateTimeFormat("pt-BR",{weekday:"long",hour:"2-digit",minute:"2-digit",timeZone:"America/Bahia"}).format(new Date(startsAt));const kind=eventKindLabel(eventType);let failed=0;for(const guardian of guardians){const {error}=await supabase.rpc("send_curio_family_message",{p_student_id:studentId,p_guardian_id:guardian.guardian_id,p_subject:`Rotina semanal de ${studentName} cadastrada`,p_body:`Olá, ${guardian.guardian_name||"responsável"}! A rotina “${title}” foi cadastrada por ${weeks} semanas, sempre ${weekday}. A primeira ${kind} será em ${first}. Cada ocorrência aparece separadamente na Agenda e pode ser atualizada se houver mudança.`,p_action_label:"Ver agenda",p_action_url:"/familia/agenda",p_request_key:`agenda-series:${seriesId}:${guardian.guardian_id}`});if(error){failed++;console.error("Falha ao avisar série semanal",error.code);}}return{attempted:guardians.length,failed};}
function revalidateAgenda(){for(const path of ["/professor/agenda","/professor","/professor/alunos","/professor/limites","/aluno/agenda","/aluno","/familia/agenda","/familia/mensagens","/familia"])revalidatePath(path);}

export async function createAgendaEvent(formData:FormData){
  const parsed=agendaSchema.safeParse({idempotencyKey:formData.get("idempotencyKey"),studentId:formData.get("studentId"),title:formData.get("title"),description:String(formData.get("description")||""),eventType:formData.get("eventType"),status:formData.get("status")||"scheduled",startsAt:formData.get("startsAt"),endsAt:String(formData.get("endsAt")||""),meetingUrl:String(formData.get("meetingUrl")||""),location:String(formData.get("location")||""),recurrence:formData.get("recurrence")||"once",repeatWeeks:formData.get("repeatWeeks")||4});
  if(!parsed.success)redirect(`/professor/agenda?erro=${encodeURIComponent(parsed.error.issues[0]?.message||"Confira os dados do encontro.")}`);const startsAt=bahiaDateTime(parsed.data.startsAt);const endsAt=bahiaDateTime(parsed.data.endsAt);if(!startsAt)redirect(`/professor/agenda?erro=${encodeURIComponent("Informe uma data e horário válidos.")}`);if(endsAt&&new Date(endsAt)<=new Date(startsAt))redirect(`/professor/agenda?erro=${encodeURIComponent("O término precisa ser depois do início.")}`);
  const {teacher,supabase}=await getCurrentTeacher();if(!teacher)redirect(`/professor/agenda?erro=${encodeURIComponent("Seu perfil de professor ainda não está vinculado.")}`);const {data:linkedStudent,error:linkError}=await supabase.from("teacher_students").select("student_id,students(preferred_name,full_name,deleted_at)").eq("teacher_id",teacher.id).eq("student_id",parsed.data.studentId).eq("active",true).maybeSingle();const studentRelation:any=(linkedStudent as any)?.students;const linkedStudentData=Array.isArray(studentRelation)?studentRelation[0]:studentRelation;if(linkError||!linkedStudent||!linkedStudentData||linkedStudentData.deleted_at)redirect(`/professor/agenda?erro=${encodeURIComponent("Este aluno não está vinculado ao seu acompanhamento ativo.")}`);
  const visibleToGuardian=formData.get("visibleToGuardian")==="on";const args={p_idempotency_key:parsed.data.idempotencyKey,p_student_id:parsed.data.studentId,p_title:parsed.data.title,p_description:parsed.data.description||"",p_event_type:parsed.data.eventType,p_starts_at:startsAt,p_ends_at:endsAt,p_meeting_url:parsed.data.meetingUrl||"",p_location:parsed.data.location||"",p_visible_to_student:formData.get("visibleToStudent")==="on",p_visible_to_guardian:visibleToGuardian};let eventIds:string[]=[];
  if(parsed.data.recurrence==="weekly"){const {data,error}=await supabase.rpc("create_teacher_agenda_series",{...args,p_repeat_weeks:parsed.data.repeatWeeks});if(error||!data){const planMessage=planLimitErrorMessage(error);redirect(`/professor/agenda?erro=${encodeURIComponent(planMessage||"Não foi possível criar a série semanal.")}`);}eventIds=(data??[]).map(String);}else{const {data,error}=await supabase.rpc("create_teacher_agenda_event",args);if(error||!data){const planMessage=planLimitErrorMessage(error);redirect(`/professor/agenda?erro=${encodeURIComponent(planMessage||"Não foi possível criar o encontro.")}`);}eventIds=[String(data)];}
  if(parsed.data.status!=="scheduled"&&eventIds.length){const {error}=await supabase.from("agenda_events").update({status:parsed.data.status,updated_at:new Date().toISOString()}).in("id",eventIds).eq("created_by_teacher_id",teacher.id);if(error)redirect(`/professor/agenda?erro=${encodeURIComponent(planLimitErrorMessage(error)||"Os encontros foram criados, mas o status precisa ser atualizado novamente.")}`);}
  let noticeFailed=0;if(visibleToGuardian&&parsed.data.status!=="completed"){const studentName=linkedStudentData.preferred_name||linkedStudentData.full_name||"Aluno";if(parsed.data.recurrence==="weekly"){const notice=await sendAgendaFamilySeriesNotice({supabase,studentId:parsed.data.studentId,studentName,title:parsed.data.title,eventType:parsed.data.eventType,startsAt,seriesId:eventIds[0]||parsed.data.idempotencyKey,weeks:parsed.data.repeatWeeks});noticeFailed=notice.failed;}else{const notice=await sendAgendaFamilyNotice({supabase,studentId:parsed.data.studentId,studentName,title:parsed.data.title,eventType:parsed.data.eventType,startsAt,eventId:eventIds[0],status:parsed.data.status});noticeFailed=notice.failed;}}
  revalidateAgenda();const countText=parsed.data.recurrence==="weekly"?`${eventIds.length} aulas/revisões semanais criadas.`:"Encontro salvo.";const success=noticeFailed?`${countText} Um aviso interno da família não pôde ser enviado; a Agenda continua correta.`:visibleToGuardian?`${countText} A família recebeu um aviso interno com a programação.`:`${countText} Disponível para os participantes selecionados.`;redirect(`/professor/agenda?sucesso=${encodeURIComponent(success)}`);
}

export async function setAgendaEventStatus(formData:FormData){
  const parsed=z.object({eventId:z.string().uuid(),status:z.enum(["scheduled","confirmed","completed","cancelled"])}).safeParse({eventId:formData.get("eventId"),status:formData.get("status")});if(!parsed.success)redirect(`/professor/agenda?erro=${encodeURIComponent("Não foi possível identificar o encontro ou a situação escolhida.")}`);const {teacher,supabase}=await getCurrentTeacher();if(!teacher)redirect(`/professor/agenda?erro=${encodeURIComponent("Seu perfil de professor ainda não está vinculado.")}`);const {data:event,error:eventError}=await supabase.from("agenda_events").select("id,title,event_type,starts_at,visible_to_guardian").eq("id",parsed.data.eventId).eq("created_by_teacher_id",teacher.id).maybeSingle();if(eventError||!event)redirect(`/professor/agenda?erro=${encodeURIComponent("Encontro não encontrado ou sem permissão para edição.")}`);const {error}=await supabase.from("agenda_events").update({status:parsed.data.status,updated_at:new Date().toISOString()}).eq("id",parsed.data.eventId).eq("created_by_teacher_id",teacher.id);if(error)redirect(`/professor/agenda?erro=${encodeURIComponent(planLimitErrorMessage(error)||"Não foi possível atualizar o encontro.")}`);
  let noticeFailed=0;if(event.visible_to_guardian&&["confirmed","cancelled"].includes(parsed.data.status)){const {data:assignments,error:assignmentsError}=await supabase.from("agenda_event_students").select("student_id,students(preferred_name,full_name)").eq("event_id",parsed.data.eventId);if(assignmentsError){noticeFailed++;}else for(const assignment of assignments??[]){const studentValue:any=(assignment as any).students;const student=Array.isArray(studentValue)?studentValue[0]:studentValue;const notice=await sendAgendaFamilyNotice({supabase,studentId:assignment.student_id,studentName:student?.preferred_name||student?.full_name||"Aluno",title:event.title,eventType:event.event_type,startsAt:event.starts_at,eventId:event.id,status:parsed.data.status});noticeFailed+=notice.failed;}}
  revalidateAgenda();const message=noticeFailed?"Situação atualizada. Um aviso interno não pôde ser entregue; a Agenda já mostra a informação correta.":parsed.data.status==="cancelled"?"Encontro cancelado e família vinculada avisada no portal.":parsed.data.status==="confirmed"?"Encontro confirmado e família vinculada avisada no portal.":"Situação do encontro atualizada.";redirect(`/professor/agenda?sucesso=${encodeURIComponent(message)}`);
}
